/**
 * Filesystem view of the docs collection.
 *
 * `astro:content` only exists inside an Astro build, but the Markdown mirror and
 * the AI skills are both generated by plain node scripts, so they read the MDX
 * off disk instead. Product docs are symlinked into `src/content/docs/<product>`
 * by `pnpm assemble`, so the walk has to follow symlinks — the whole tree lives
 * behind one.
 */
import fg from "fast-glob";
import { readFileSync } from "node:fs";
import path from "node:path";

import { DOCS_SOURCES } from "../sitemap/docs-sources";
// The `.ts` extension is load-bearing: Node resolves a relative specifier
// ending in `.node` as a native addon, so `pnpm gen:markdown` / `gen:skills`
// (plain tsx, no bundler) cannot find this module without it.
import { docsRoot } from "../sitemap/docs-sources.node.ts";
import { getProductMetadata } from "../sitemap/product-metadata";
import { deploySlugForContentId } from "../sitemap/deploy";
import { GUIDES_ROUTE_PREFIX, guidesSlugForContentId, SITE_GUIDES } from "../sitemap/guides";
import { listSnippetFiles, mdxToMarkdown } from "./mdx-to-markdown";
import { isRoutedDocsContentId, normalizeSlug, PROJECT_ROOT } from "./shared";

const CONTENT_BASE = path.join(PROJECT_ROOT, "src/content/docs");
// Website-owned product overviews, which shadow each bundle's docs root on the
// site (see src/pages/[product]/[tab]/[...slug].astro).
const OVERVIEWS_BASE = path.join(PROJECT_ROOT, "src/content/overviews");
// Website-owned solution guides, routed onto the Guides tab (see
// src/pages/guides/[...slug].astro).
const GUIDES_BASE = path.join(PROJECT_ROOT, "src/content/guides");

export interface DocPage {
	/** Product id, i.e. the first slug segment. */
	product: string;
	/** Site path without a leading slash, e.g. `actors/docs/state`. */
	slug: string;
	title: string;
	description: string;
	/** Absolute path to the source `.mdx`. */
	sourcePath: string;
	/** Raw MDX body, frontmatter stripped. */
	body: string;
	/** `examples/...` paths this page embeds, relative to its snippet root. */
	snippetFiles: string[];
}

let cache: DocPage[] | null = null;

export function listDocPages(): DocPage[] {
	if (cache) return cache;

	const files = fg
		.sync("**/*.mdx", { cwd: CONTENT_BASE, followSymbolicLinks: true })
		.sort();

	const pages: DocPage[] = [];
	for (const file of files) {
		const product = file.split("/")[0];
		if (!DOCS_SOURCES[product]) {
			throw new Error(
				`src/content/docs/${file} is not under a known product. ` +
					`Add the product to src/sitemap/product-metadata.ts or move the page.`,
			);
		}

		const sourcePath = path.join(CONTENT_BASE, file);
		const raw = readFileSync(sourcePath, "utf-8");
		const { frontmatter, body } = splitFrontmatter(raw);
		const title = frontmatterValue(frontmatter, "title");
		const description = frontmatterValue(frontmatter, "description");
		if (!title) {
			throw new Error(`src/content/docs/${file} has no frontmatter title`);
		}

		// Most bundles are served at their content id; the Rivet Cloud bundle
		// renders inside the Deploy section and the Actors `learn` section as
		// the Guides tab instead.
		const contentId = normalizeSlug(file.replace(/\.mdx$/, ""));
		// Shared bundles (agentOS -> Sandboxes) are walked twice; only the
		// product that routes them gets a Markdown mirror and search entries.
		if (!isRoutedDocsContentId(contentId)) continue;
		pages.push({
			product,
			slug: deploySlugForContentId(contentId) ?? guidesSlugForContentId(contentId) ?? contentId,
			title,
			description: description ?? "",
			sourcePath,
			body,
			snippetFiles: listSnippetFiles(body),
		});
	}

	if (pages.length === 0) {
		throw new Error(
			`No .mdx found under ${CONTENT_BASE}. Run \`pnpm assemble\` to link ` +
				`each product's docs in.`,
		);
	}

	for (const file of fg.sync("*.mdx", { cwd: OVERVIEWS_BASE }).sort()) {
		const product = file.replace(/\.mdx$/, "");
		const sourcePath = path.join(OVERVIEWS_BASE, file);
		const raw = readFileSync(sourcePath, "utf-8");
		const { frontmatter, body } = splitFrontmatter(raw);
		const title = frontmatterValue(frontmatter, "title");
		if (!title) {
			throw new Error(`src/content/overviews/${file} has no frontmatter title`);
		}
		const slug = `${product}/docs`;
		const page: DocPage = {
			product,
			slug,
			title,
			description: frontmatterValue(frontmatter, "description") ?? "",
			sourcePath,
			body,
			snippetFiles: listSnippetFiles(body),
		};
		const index = pages.findIndex((candidate) => candidate.slug === slug);
		if (index === -1) pages.push(page);
		else pages[index] = page;
	}

	for (const guide of SITE_GUIDES) {
		const sourcePath = path.join(GUIDES_BASE, `${guide.slug}.mdx`);
		const raw = readFileSync(sourcePath, "utf-8");
		const { frontmatter, body } = splitFrontmatter(raw);
		pages.push({
			product: "actors",
			slug: normalizeSlug(`${GUIDES_ROUTE_PREFIX.slice(1)}/${guide.slug}`),
			title: frontmatterValue(frontmatter, "title") ?? guide.title,
			description: frontmatterValue(frontmatter, "description") ?? "",
			sourcePath,
			body,
			snippetFiles: listSnippetFiles(body),
		});
	}

	cache = pages;
	return pages;
}

/** Repo root a product's `examples/...` snippet paths resolve against. */
export function snippetRootFor(product: string): string | undefined {
	return docsRoot(product);
}

/** `github.com/rivet-dev/<repo>` that owns a product's examples. */
export function examplesRepoFor(product: string): string {
	const owner = getProductMetadata(product);
	if (!owner) throw new Error(`Unknown product: ${product}`);
	return `rivet-dev/${owner.repo}`;
}

/** The page as plain Markdown, with `<CodeSnippet>` targets inlined. */
export function renderDocMarkdown(page: DocPage): string {
	return mdxToMarkdown(page.body, {
		snippetRoot: snippetRootFor(page.product),
		sourceLabel: page.slug,
	});
}

export function splitFrontmatter(raw: string) {
	const match = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
	if (!match) return { frontmatter: "", body: raw };
	return { frontmatter: match[1], body: match[2] };
}

export function frontmatterValue(frontmatter: string, key: string) {
	const match = frontmatter.match(
		new RegExp(`^${key}:[ \\t]*(.+?)[ \\t]*$`, "m"),
	);
	if (!match) return undefined;
	return match[1].replace(/^["'](.*)["']$/s, "$1").trim();
}
