#!/usr/bin/env node
// @ts-nocheck
//
// RIVET ICONS VENDOR SCRIPT
// This script is for Rivet maintainers only.
// It generates icon files from Font Awesome Pro packages.
//
// LEGAL NOTICE: The generated icons are licensed exclusively for use in Rivet
// products and services. Using these icons in any other product or project is
// strictly prohibited and may violate Font Awesome's Terms of Service.
//

import fs from "node:fs";
import { join, resolve } from "node:path";
import dedent from "dedent";
import esbuild from "esbuild";
import {
	PATHS,
	log,
	error,
	exitWithError,
	checkEnvironment,
	setupSourceDirectory,
	configureFontAwesomeRegistry,
	installFontAwesomePackages,
	cleanupGeneratedFiles,
} from "./shared-utils.js";

// ============================================================================
// CONFIGURATION
// ============================================================================

const LEGAL_BANNER = dedent`
	// @ts-nocheck
	// This file is generated by scripts/vendor-icons.js
	// Do not modify this file directly
	// This file includes Font Awesome Pro icons
	//
	// LEGAL NOTICE: This package is licensed exclusively for use in Rivet products
	// and services. Using this package in any other product or project is strictly
	// prohibited and may violate Font Awesome's Terms of Service.


`;

// ============================================================================
// ICON GENERATION PHASE
// ============================================================================

function loadManifest() {
	log("📋", "Loading icon manifest...");
	try {
		const manifest = JSON.parse(fs.readFileSync(PATHS.manifest, "utf-8"));
		const packageCount = Object.keys(manifest).length;
		const iconCount = Object.values(manifest).reduce(
			(sum, pkg) => sum + pkg.icons.length,
			0,
		);
		log("📊", `Loaded ${iconCount} icons from ${packageCount} packages`);
		return manifest;
	} catch (err) {
		const message = err instanceof Error ? err.message : String(err);
		exitWithError(`Failed to load manifest: ${message}`);
	}
}

/**
 * @param {string} pkg
 * @param {string} iconName
 */
function checkIconExists(pkg, iconName) {
	const candidate = join(PATHS.srcNodeModules, pkg, `${iconName}.js`);
	return fs.existsSync(candidate);
}

/**
 * @typedef {{ name: string, source: string, inlineCode: null } | { name: string, source: null, inlineCode: string }} IconEntry
 */

/**
 * @param {string} pkg
 * @param {string} iconName
 * @param {string} exportName
 * @returns {IconEntry}
 */
function makeIconEntry(pkg, iconName, exportName) {
	const exists = checkIconExists(pkg, iconName);
	const sourcePkg = exists ? `${pkg}/${iconName}` : "@fortawesome/free-solid-svg-icons/faSquare";
	return { name: exportName, source: sourcePkg, inlineCode: null };
}

/**
 * @param {string} pkg
 * @param {Array<{icon: string, aliases: string[]}>} icons
 * @returns {{ entries: IconEntry[], count: number }}
 */
function processCustomPackage(pkg, icons) {
	const entries = icons.map(({ icon }) => ({ name: icon, source: pkg, inlineCode: null }));
	return { entries, count: entries.length };
}

/**
 * Process legacy custom packages (duotone icons from JS files).
 * These need to be inlined as the legacy format is not ES module compatible.
 * @param {string} pkg
 * @param {Array<{icon: string, aliases: string[]}>} icons
 * @returns {{ entries: IconEntry[], count: number }}
 */
function processLegacyCustomPackage(pkg, icons) {
	const jsFilePath = join(PATHS.srcNodeModules, pkg);
	const jsContent = fs.readFileSync(jsFilePath, "utf-8");

	// The format is: var icons = { "iconName": [width, height, aliases, unicode, pathData], ... }
	const iconsMatch = jsContent.match(/var\s+icons\s*=\s*(\{[\s\S]*?\});/);
	if (!iconsMatch) {
		return { entries: [], count: 0 };
	}

	const iconsObj = JSON.parse(iconsMatch[1]);
	const entries = [];

	for (const { icon } of icons) {
		// Convert faIconName back to icon-name
		const baseName = icon
			.replace(/^fa/, "")
			.replace(/([A-Z])/g, "-$1")
			.toLowerCase()
			.replace(/^-/, "");

		const iconData = iconsObj[baseName];
		if (!iconData) continue;

		// FontAwesome icon format: [width, height, aliases, unicode, pathData]
		const [width, height, , unicode, pathData] = iconData;
		const iconDef = { prefix: "fakd", iconName: baseName, icon: [width, height, [], unicode, pathData] };
		entries.push({ name: icon, source: null, inlineCode: `export const ${icon} = ${JSON.stringify(iconDef)};` });
	}

	return { entries, count: entries.length };
}

/**
 * @param {string} pkg
 * @param {Array<{icon: string, aliases: string[]}>} icons
 * @param {Set<string>} existingExports
 * @returns {{ entries: IconEntry[], count: number }}
 */
function processStandardPackage(pkg, icons, existingExports) {
	const entries = [];

	for (const { icon, aliases } of icons) {
		if (!existingExports.has(icon)) {
			entries.push(makeIconEntry(pkg, icon, icon));
			existingExports.add(icon);
		}

		for (const alias of aliases) {
			if (alias === icon || existingExports.has(alias)) continue;
			entries.push(makeIconEntry(pkg, icon, alias));
			existingExports.add(alias);
		}
	}

	return { entries, count: entries.length };
}

/**
 * @param {Record<string, {icons: Array<{icon: string, aliases: string[]}>}>} manifest
 * @returns {{ iconCode: string, iconEntries: IconEntry[] }}
 */
function generateIconExports(manifest) {
	log("🎨", "Generating icon exports...");

	const existingExports = new Set();
	/** @type {IconEntry[]} */
	const iconEntries = [];
	let totalIcons = 0;
	const stats = { custom: 0, pro: 0, free: 0 };

	for (const [pkg, { icons }] of Object.entries(manifest)) {
		const isLegacyCustom = pkg.endsWith(".js");
		const isCustom = pkg.startsWith("@awesome.me/kit-") && !isLegacyCustom;
		const isPro = pkg.startsWith("@fortawesome/pro-");

		let result;
		if (isLegacyCustom) {
			result = processLegacyCustomPackage(pkg, icons);
		} else if (isCustom) {
			result = processCustomPackage(pkg, icons);
		} else {
			result = processStandardPackage(pkg, icons, existingExports);
		}

		iconEntries.push(...result.entries);
		totalIcons += result.count;

		if (isCustom || isLegacyCustom) stats.custom += result.count;
		else if (isPro) stats.pro += result.count;
		else stats.free += result.count;
	}

	// Build the code string for .gen.js / .gen.ts from the structured entries.
	// Custom packages use a single bulk export line grouped by source.
	const bulkSources = new Map();
	let iconCode = "";
	for (const entry of iconEntries) {
		if (entry.inlineCode) {
			iconCode += `${entry.inlineCode}\n`;
		} else if (entry.source?.startsWith("@awesome.me/")) {
			const names = bulkSources.get(entry.source) ?? [];
			names.push(entry.name);
			bulkSources.set(entry.source, names);
		} else {
			iconCode += `export { definition as ${entry.name} } from "${entry.source}";\n`;
		}
	}
	for (const [source, names] of bulkSources) {
		iconCode += `export { ${names.join(", ")} } from "${source}";\n`;
	}

	log("✅", `Generated ${totalIcons} icon exports`);
	log("📊", `  Free: ${stats.free} | Pro: ${stats.pro} | Custom: ${stats.custom}`);

	return { iconCode, iconEntries };
}

/**
 * @param {string} iconCode
 */
function generateJavaScriptFile(iconCode) {
	log("📝", "Generating src/index.gen.js...");

	const baseCode = dedent`
		import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
		import { createElement } from "react";
		export function Icon(props) { return createElement(FontAwesomeIcon, props)}
	`;

	const content = LEGAL_BANNER + "\n" + baseCode + "\n" + iconCode;
	fs.writeFileSync(join(PATHS.src, "index.gen.js"), content);

	const sizeKB = (Buffer.byteLength(content, "utf8") / 1024).toFixed(2);
	log("✅", `Generated src/index.gen.js (${sizeKB} KB)`);
}

/**
 * @param {string} iconCode
 */
function generateTypeScriptFile(iconCode) {
	log("📝", "Generating src/index.gen.ts...");

	const baseCode = dedent`
		import { FontAwesomeIcon, FontAwesomeIconProps } from "@fortawesome/react-fontawesome";
		import { ComponentProps, createElement } from "react";
		export function Icon(props: Omit<ComponentProps<typeof FontAwesomeIcon>, 'icon'> & {icon: IconProp}) { return createElement(FontAwesomeIcon, props as FontAwesomeIconProps)}
		export type IconProp = string | { prefix: string; iconName: string } | [string, string];
	`;

	const content = LEGAL_BANNER + "\n" + baseCode + "\n" + iconCode;
	fs.writeFileSync(join(PATHS.src, "index.gen.ts"), content);

	const sizeKB = (Buffer.byteLength(content, "utf8") / 1024).toFixed(2);
	log("✅", `Generated src/index.gen.ts (${sizeKB} KB)`);
}

// ============================================================================
// BUNDLING PHASE
// ============================================================================

/**
 * @param {IconEntry[]} iconEntries
 */
async function bundleWithEsbuild(iconEntries) {
	log("📦", "Bundling with esbuild (per-icon files for ESM tree-shaking)...");

	const extPackages = [
		"react",
		"react-dom",
		"@fortawesome/react-fontawesome",
	];

	const distDir = resolve(PATHS.dist);
	if (fs.existsSync(distDir)) {
		fs.rmSync(distDir, { recursive: true, force: true });
	}
	fs.mkdirSync(distDir, { recursive: true });
	fs.mkdirSync(resolve(distDir, "icons"), { recursive: true });

	const entryDir = resolve(PATHS.src, "_entries");
	if (fs.existsSync(entryDir)) {
		fs.rmSync(entryDir, { recursive: true, force: true });
	}
	fs.mkdirSync(entryDir, { recursive: true });

	try {
		log("📊", `Building ${iconEntries.length} icon entry files`);

		// Build each icon into its own dist/icons/<name>.js file.
		// No splitting — each icon file is self-contained and includes its SVG data.
		//
		// Some icon names are case-equivalent aliases (e.g. faPaintBrush /
		// faPaintbrush). esbuild uses the entry key as the output path, so two keys
		// that differ only in case would collide on case-insensitive file systems.
		// For the secondary alias we skip the esbuild entry and instead write a
		// thin static re-export file directly into dist/icons/ after the build.
		const entryPoints = {};
		const seenLower = new Map(); // lowercase name -> primary export name
		/** @type {Array<{name: string, primaryName: string}>} */
		const deferredAliases = [];

		for (const { name, source, inlineCode } of iconEntries) {
			const lower = name.toLowerCase();
			if (seenLower.has(lower)) {
				deferredAliases.push({ name, primaryName: seenLower.get(lower) });
				continue;
			}
			seenLower.set(lower, name);
			const entryFile = join(entryDir, `${name}.js`);
			let code;
			if (inlineCode) {
				code = `${inlineCode}\n`;
			} else if (source.startsWith("@awesome.me/")) {
				// Custom kit: source is the package path, export by name directly
				code = `export { ${name} } from "${source}";\n`;
			} else {
				// Standard/pro: source is a subpath file exporting `definition`
				code = `export { definition as ${name} } from "${source}";\n`;
			}
			fs.writeFileSync(entryFile, code);
			entryPoints[`icons/${name}`] = entryFile;
		}

		// Build the Icon component entry separately (no icon data included).
		const iconComponentEntry = join(entryDir, "_icon-component.js");
		fs.writeFileSync(
			iconComponentEntry,
			`import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";\nimport { createElement } from "react";\nexport function Icon(props) { return createElement(FontAwesomeIcon, props); }\n`,
		);
		entryPoints["icon-component"] = iconComponentEntry;

		await esbuild.build({
			entryPoints,
			outdir: distDir,
			external: extPackages.flatMap((pkg) => [pkg, `${pkg}/*`]),
			bundle: true,
			splitting: false,
			platform: "neutral",
			format: "esm",
			treeShaking: true,
		});

		// Build a map of deferred alias name -> primary name for the barrel.
		// We do NOT write separate alias files because on case-insensitive file
		// systems the deferred file would overwrite the esbuild-generated primary.
		// Instead, the barrel re-exports the alias name directly from the primary file.
		/** @type {Map<string, string>} */
		const aliasToPrimary = new Map(deferredAliases.map(({ name, primaryName }) => [name, primaryName]));

		// Generate a pure static re-export barrel so consumers can do:
		//   import { faCheck } from "@rivet-gg/icons"
		// and their bundler will tree-shake via the static re-exports.
		const allNames = iconEntries.map(({ name }) => name);
		let barrelLines = "";
		for (const name of allNames) {
			const primaryName = aliasToPrimary.get(name);
			if (primaryName) {
				// Alias: re-export from the primary file under the alias name.
				barrelLines += `export { ${primaryName} as ${name} } from "./icons/${primaryName}.js";\n`;
			} else {
				barrelLines += `export { ${name} } from "./icons/${name}.js";\n`;
			}
		}
		barrelLines += `export { Icon } from "./icon-component.js";\n`;
		const barrelPath = resolve(distDir, "index.barrel.js");
		fs.writeFileSync(barrelPath, barrelLines);
		fs.renameSync(barrelPath, resolve(distDir, "index.js"));

		// Clean up temp entry files
		fs.rmSync(entryDir, { recursive: true, force: true });

		const indexStats = fs.statSync(resolve(distDir, "index.js"));
		const iconFiles = fs.readdirSync(resolve(distDir, "icons")).length;
		log("✅", `Generated dist/ (barrel: ${(indexStats.size / 1024).toFixed(2)} KB, ${iconFiles} icon files)`);
	} catch (err) {
		// Clean up temp entry files on failure too
		if (fs.existsSync(entryDir)) {
			fs.rmSync(entryDir, { recursive: true, force: true });
		}
		const message = err instanceof Error ? err.message : String(err);
		exitWithError(`Build failed: ${message}`);
	}
}

// ============================================================================
// MAIN
// ============================================================================

async function main() {
	console.log("\n🚀 Rivet Icons Vendor Script\n");

	// Check environment before creating any files
	checkEnvironment();

	// Setup and generate with guaranteed cleanup
	setupSourceDirectory();
	try {
		configureFontAwesomeRegistry();
		installFontAwesomePackages();

		console.log();

		// Generation phase
		const manifest = loadManifest();
		const { iconCode, iconEntries } = generateIconExports(manifest);
		generateJavaScriptFile(iconCode);
		generateTypeScriptFile(iconCode);

		console.log();

		// Bundle phase: produce individual icon chunks + barrel index
		await bundleWithEsbuild(iconEntries);

		// Success!
		console.log("\n🎉 Done! All files generated and ready to commit:");
		console.log("   - src/index.gen.js");
		console.log("   - src/index.gen.ts");
		console.log("   - dist/index.js");
		console.log("   - dist/icons/*.js (per-icon chunks)");
		console.log("\n💡 Next steps:");
		console.log("   1. Review the generated files");
		console.log("   2. Commit them to git");
		console.log("   3. Consumers can now use the package without any FA token!");
		console.log();
	} finally {
		console.log();
		cleanupGeneratedFiles();
	}
}

// Run the script
main().catch((err) => {
	const message = err instanceof Error ? err.message : String(err);
	error(`Unexpected error: ${message}`);
	if (err instanceof Error && err.stack) {
		console.error(err.stack);
	}
	process.exit(1);
});
